version: '3.9'

services:
  db-s:
    container_name: db-s
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db-s
    networks:
      - app_network

  command:
    container_name: commands
    image: soulaiamansoulb/commands
    ports:
      - "5001:4001"
    depends_on:
      - db-s
    environment:
      - MONGODB_URI=mongodb://db-s:27017/commands
    networks:
      - app_network

  produits:
    container_name: produits
    image: soulaiamansoulb/products
    ports:
      - "5002:4000"
    depends_on:
      - db-s
      - command

    environment:
      - MONGODB_URI=mongodb://db-s:27017/produits
    networks:
      - app_network

  auth-s:
    container_name: auth-s
    image: soulaiamansoulb/auth
    ports:
      - "5003:4002"
    depends_on:
      - db-s
      - produits
    environment:
      - MONGODB_URI=mongodb://db-s:27017/users  
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  data:
